# Generated by Django 3.1.2 on 2021-09-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
