# Generated by Django 3.1.2 on 2021-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('ngo_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
