# Generated by Django 3.2.7 on 2021-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0002_auto_20210915_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ngo_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
