# Generated by Django 3.2.7 on 2021-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0003_alter_user_ngo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ngo_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
