# Generated by Django 3.2.7 on 2021-09-29 09:28

from django.db import migrations, models
import donor_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0004_alter_user_ngo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10, validators=[donor_api.models.validate_contact]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=8, validators=[donor_api.models.validate_pwd]),
        ),
    ]
