# Generated by Django 3.2.7 on 2021-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0005_auto_20210929_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('cont_no', models.CharField(max_length=10)),
                ('food_type', models.CharField(max_length=200)),
                ('cdt', models.CharField(max_length=200)),
                ('pdt', models.CharField(max_length=10)),
                ('ploc', models.TextField()),
            ],
        ),
    ]
