# Generated by Django 3.2.7 on 2021-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0007_alter_donateform_pdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('cont_no', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
