# Generated by Django 3.2.7 on 2022-01-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0008_feedbackform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_id', models.CharField(max_length=2000)),
            ],
        ),
    ]
